### ISSUE TITLE
As a world leader

### ISSUE THREAD

**Issue by thonisett** [Benbhoy1888/SET08103#10]
**User Story**

As a world leader, 

- I want to produce reports that show all capital cities organised by population large to small for; the world, a continent or a region.
- 
- I would also like the option to be able to input the top N to display. 

This is so I can view where to target the nukes.

**Acceptance Criteria** 

Given the reports are selected from a menu when the world leader selects Capital city report, then they will have options to select from world, continent or region categories.

When the world leader enters their selection, then the report should be generated displaying the correct capital cities from the correct category.

This should contain the columns: Name, Country and Population.

**Comment by Andy-Dickinson** [comment]
@emma123456789101 Whats the latest on this?

**Comment by Andy-Dickinson** [comment]
@emma123456789101 These still aren't being generated and there are lots of errors on your branch for this. I'm going to start it again from scratch
