### ISSUE TITLE
As a disaster risk management planner

### ISSUE THREAD

**Issue by thonisett** [Benbhoy1888/SET08103#11]
**User Story**

As a disaster risk management planner,

- I want to produce reports that show all cities organised by population large to small for; the world, a continent, a region, a country or a district. 

- I would also like the option to be able to input the top N to display.

This is so I can view which cities are most populated and where risk planning should be focused.

**Acceptance Criteria**

Given the reports are selected from a menu when the planner selects city report, then they will have options to select from world, continent, region, country or district categories.

When the planner enters their selection, then the report should be generated displaying the correct cities from the correct category.

This should contain the columns: Name, Country, District and Population.

**Comment by Andy-Dickinson** [comment]
@Ben-Loughrey is this done?
