### ISSUE TITLE
capital city report test missing

### ISSUE THREAD

**Issue by Andy-Dickinson** [Benbhoy1888/SET08103#37]
Capital city report test has gone missing. Requires investigation

**Comment by Andy-Dickinson** [comment]
Looks like you deleted it in an old commit.
If you go to this link and one suggestion is copy it out, recreate the test file and add it back in.

https://github.com/Benbhoy1888/SET08103/blob/8bd5bab854e27993c57b21958eacddb49895072a/src/test/java/com/napier/sem/CapitalCityReportTests.java

**Comment by emma123456789101** [comment]
currently trying to fix this though there are still some errors just to let you guys know

**Comment by emma123456789101** [comment]
this is late to write but fixed the errors passing all tests on github :)
