### ISSUE TITLE
[BUG] errors-in-develop

### ISSUE THREAD

**Issue by emma123456789101** [Benbhoy1888/SET08103#42]
**Describe the bug**
there are two languages defined please look at this

**To Reproduce**
1. Go to 'develop'
2. Click on 'the app'
3. Scroll down to 'languages'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by emma123456789101** [comment]
IN THE APP INTEGRATION TEST THERE IS A LANGUAGE.CODE AS AN ERROR

**Comment by thonisett** [comment]
Issues now correct - duplicated language tests removed, CapitalReportTest class name corrected and method names corrected
