### ISSUE TITLE
CapitalReporttest failing

### ISSUE THREAD

**Issue by thonisett** [Benbhoy1888/SET08103#43]
outputCapitalCitiesReportsN_MoreThanInListTest method in CapitalReportTests is failing with the following error message
outputCapitalCitiesReportsN_MoreThanInListTest on line 101

**Comment by thonisett** [comment]
Closed - issue due to re-running code whilst intellji was still building

**Comment by Andy-Dickinson** [comment]
Was missing password in db/dockerfile. 
Database now works, so you can continue looking into the other errors now generated for your capital city reports

**Comment by Andy-Dickinson** [comment]
There are still lots of errors on your branch for this, I'm going to restart the capital reports from scratch
